services:

  app:
    build: .
    container_name: logistics-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/logistics_db
    depends_on:
      - mongodb


  mongodb:
    image: 'mongo:latest'
    container_name: logistics-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=logistics_db'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: